Repository ngnrsaa/qflex, pull requests merged in 2019-11, with the labels that each got.

#209 Fix check_format.sh to work on Mac OSX and on Travis (YAPF)
  .clang-format
  .style.yapf
  .travis.yml
  scripts/check_format.sh
Labels: bug

#208 Adding try-catch to tests.
  src/contraction_utils.cpp
  src/read_circuit.cpp
  tests/src/contraction_utils_test.cpp
  tests/src/evaluate_circuit_test.cpp
  tests/src/read_circuit_test.cpp
  tests/src/tensor_test.cpp
Labels: testing

#211 Run qFlex natively on Mac OSX using clang
  Makefile.in
  configure.ac
  docs/install.md
  src/Makefile.in
  src/errors.h
  src/read_circuit.cpp
  tests/src/tensor_test.cpp
Labels: enhancement

#215 Remove qflex-base@docker.
  .travis.yml
  Dockerfile
  Makefile.in
  README.md
  docker-compose.yml
  docs/docker.md
  src/Dockerfile
  tests/python/Dockerfile
  tests/src/Dockerfile
Labels: enhancement

#218 Adding more context to tensor.cpp method calls
  src/contraction_utils.cpp
  src/read_circuit.cpp
  src/tensor.cpp
Labels: enhancement

#223 Update docs.
  README.md
  docs/install.md
Labels: documentation

#228 Fix string catch.
  src/contraction_utils.cpp
  src/read_circuit.cpp
  src/tensor.cpp
Labels: LGTM

#220 Improve dockerfile (depends on: #215)
  Dockerfile
  tests/python/Dockerfile
  tests/src/Dockerfile
Labels: enhancement

#229 Fix index_value (depends on: #228)
  src/tensor.cpp
Labels: LGTM

#227 Fix circuit.load()
  src/circuit.cpp
  src/circuit.h
  src/grid.cpp
  src/grid.h
  src/ordering.cpp
  src/ordering.h
  src/read_circuit.cpp
  tests/src/read_circuit_test.cpp
Labels: bug, testing

#210 Pybind can use list of strings as inputs.
  config/grid/ibm_rochester.txt
  config/grid/rigetti_aspen.txt
  src/pybind_main.cpp
  src/pybind_main.h
  tests/python/simulation_test.py
Labels: enhancement

#233 Add verbose option
  src/circuit.h
  src/contraction_utils.cpp
  src/contraction_utils.h
  src/errors.h
  src/evaluate_circuit.cpp
  src/evaluate_circuit.h
  src/global.h
  src/grid.h
  src/input.h
  src/main.cpp
  src/ordering.h
  src/pybind_main.h
  src/read_circuit.h
  src/tensor.cpp
  src/tensor.h
Labels: enhancement

#232 Circuit.cpp and grid.cpp tests
  src/circuit.cpp
  src/grid.cpp
  src/grid.h
  tests/src/circuit_test.cpp
  tests/src/evaluate_circuit_test.cpp
  tests/src/grid_test.cpp
Labels: testing
