Repository ngnrsaa/qflex, pull requests merged in 2019-12, with the labels that each got.

#237 Fix check-format.py to properly exclude modules in Mac OSX.
  .clang-format
  .style.yapf
  .travis.yml
  scripts/check_format.sh
  scripts/requirements.txt
  src/evaluate_circuit.cpp
  src/read_circuit.cpp
  tests/src/read_circuit_test.cpp
  tests/src/tensor_test.cpp
Labels: enhancement

#246 Added tests for ordering.cpp
  tests/src/ordering_test.cpp
Labels: testing

#231 Try-catch for evaluate_circuit.cpp and contraction_utils.cpp
  src/contraction_utils.cpp
  src/contraction_utils.h
  src/evaluate_circuit.cpp
  src/main.cpp
  src/read_circuit.cpp
  tests/src/contraction_utils_test.cpp
  tests/src/evaluate_circuit_test.cpp
Labels: enhancement, testing

#248 Fix ordering_data_to_contraction_ordering
  src/contraction_utils.cpp
  src/contraction_utils.h
  src/evaluate_circuit.cpp
  tests/src/contraction_utils_test.cpp
Labels: testing

#241 Improve reordering tests
  tests/src/tensor_test.cpp
Labels: testing
