Repository ngnrsaa/qflex, pull requests merged in 2020-01, with the labels that each got.

#225 Improve C++ code.
  Makefile.in
  configure.ac
  docs/install.md
  src/circuit.cpp
  src/contraction_utils.cpp
  src/contraction_utils.h
  src/evaluate_circuit.cpp
  src/evaluate_circuit.h
  src/grid.cpp
  src/grid.h
  src/main.cpp
  src/read_circuit.cpp
  src/read_circuit.h
  src/tensor.cpp
  src/tensor.h
  tests/src/circuit_test.cpp
  tests/src/contraction_utils_test.cpp
  tests/src/evaluate_circuit_test.cpp
  tests/src/grid_test.cpp
  tests/src/read_circuit_test.cpp
  tests/src/tensor_test.cpp
Labels: LGTM, must do

#251 Quick fix for LGTM.
  src/read_circuit.cpp
Labels: LGTM

#252 Reduce memory requirements
  config/circuits/rochester_53_10_0_pABC.txt
  config/circuits/rochester_53_12_0_pABC.txt
  config/circuits/rochester_53_16_0_pABC.txt
  config/circuits/rochester_53_20_0_pABC.txt
  config/circuits/rochester_53_4_0_pABC.txt
  config/circuits/rochester_53_8_0_pABC.txt
  config/circuits/sycamore_53_5_0.txt
  config/grid/rochester_53.txt
  config/ordering/rochester_53.txt
  config/ordering/sycamore_53.txt
  src/contraction_utils.cpp
  src/contraction_utils.h
  src/errors.h
  src/tensor.h
  src/utils.h
Labels: enhancement

#254 Fix memory cmd argument.
  src/Makefile.in
  src/contraction_utils.cpp
  src/global.h
  src/main.cpp
  src/memory.h
  src/utils.cpp
  src/utils.h
  tests/src/Makefile.in
Labels: enhancement

#253 Track memory usage in real-time (depends on: #257).
  src/global.h
  src/main.cpp
  src/memory.h
Labels: enhancement
